// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUB6vtzKQweqLL3xfKmnQ2ULNpXK-CQ18',
    appId: '1:708290756821:web:69c7711c53392973ca225c',
    messagingSenderId: '708290756821',
    projectId: 'soulei',
    authDomain: 'soulei.firebaseapp.com',
    storageBucket: 'soulei.appspot.com',
    measurementId: 'G-RBXZRFT5YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCubEFIeKWWrxzNxU_1ZipuhSXUlCgWHcY',
    appId: '1:708290756821:android:f4c5a04474eb1ae4ca225c',
    messagingSenderId: '708290756821',
    projectId: 'soulei',
    storageBucket: 'soulei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD64egVoKMdt7cV1weOjP3yd8pN1URJpi8',
    appId: '1:708290756821:ios:abb0fc4e26058e10ca225c',
    messagingSenderId: '708290756821',
    projectId: 'soulei',
    storageBucket: 'soulei.appspot.com',
    iosBundleId: 'com.example.pandaEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD64egVoKMdt7cV1weOjP3yd8pN1URJpi8',
    appId: '1:708290756821:ios:abb0fc4e26058e10ca225c',
    messagingSenderId: '708290756821',
    projectId: 'soulei',
    storageBucket: 'soulei.appspot.com',
    iosBundleId: 'com.example.pandaEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUB6vtzKQweqLL3xfKmnQ2ULNpXK-CQ18',
    appId: '1:708290756821:web:16658f85fbbe0f16ca225c',
    messagingSenderId: '708290756821',
    projectId: 'soulei',
    authDomain: 'soulei.firebaseapp.com',
    storageBucket: 'soulei.appspot.com',
    measurementId: 'G-8TY5F06S8Y',
  );
}
